name: Build the runtime
on: workflow_dispatch
jobs:
    build:
        runs-on: ubuntu-latest
        container: ubuntu:18.04
        steps:
            - name: Checkout this repository.
              uses: actions/checkout@v3
              with:
                path: main
            - name: Clone runtimezilla
              uses: actions/checkout@v3
              with:
                repository: mirkobrombin/runtimezilla
                ref: 0.1
                path: runtimezilla 
            - name: Setup Python 
              uses: actions/setup-python@v4 

            - name: Install python deps
              run: python3 -m pip install -r runtimezilla/requirements.txt

            - name: Enable i386 arch
              run: dpkg --add-architecture i386

            - name: Update repository
              run: apt-get -qq update

            - name: Build runtime
              run: python3 runtimezilla/runtimezilla --recipe ./main/recipe.yml --output ./runtime

            - name: Compress runtime
              run: tar -czvf runtime.tar.gz runtime

            - name: Upload runtime
              uses: actions/upload-artifact@v3
              with:
                name: runtime
                path: runtime.tar.gz



