name: Build the runtime
on: 
  push:
    branches: main
    tags:
      - 'v*'
jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: ubuntu:18.04
            env:
                LANG: C.UTF-8
        steps:
            - name: Enable i386 arch
              run: dpkg --add-architecture i386

            - name: Update repository
              run: apt-get -qq update

            - name: Install python
              run: apt-get install python3 python3-pip git sudo -y

            - name: Checkout this repository.
              uses: actions/checkout@v3
              with:
                path: main
            - name: Clone runtimezilla
              uses: actions/checkout@v3
              with:
                repository: mirkobrombin/runtimezilla
                ref: 0.1
                path: runtimezilla 

            - name: Install python deps
              run: python3 -m pip install -r runtimezilla/requirements.txt

            - name: Build runtime
              env: 
                PYTHONUTF8: 1
                PYTHONIOENCODING: UTF-8
              working-directory: runtimezilla
              run: python3 runtimezilla --recipe ../main/recipe.yml --output ../runtime

            - name: Prepare runtime
              run: main/prepare.sh 

            - name: Compress runtime
              run: tar -czvf runtime.tar.gz runtime

            - name: Upload runtime
              if: github.ref_type == 'branch'
              uses: actions/upload-artifact@v3
              with:
                name: runtime
                path: runtime.tar.gz
    
            - name: Publish release
              if: github.ref_type == 'tag'
              uses: marvinpinto/action-automatic-releases@latest
              with:
                repo_token: "${{secrets.GITHUB_TOKEN}}"
                prerelease: false
                draft: false
                files: runtime.tar.gz


